CREATE TABLE [pagamento].[tb_subempenho] (
    [id_subempenho]                               INT           IDENTITY (1, 1) NOT NULL,
    [dt_cadastro]                                 DATE          NULL,
    [fl_sistema_prodesp]                          BIT           NULL,
    [fl_sistema_siafem_siafisico]                 BIT           NULL,
    [nr_prodesp]                                  VARCHAR (13)  NULL,
    [nr_siafem_siafisico]                         VARCHAR (11)  NULL,
    [nr_contrato]                                 VARCHAR (13)  NULL,
    [tb_cenario_id_cenario]                       INT           NULL,
    [nr_empenho_prodesp]                          VARCHAR (11)  NULL,
    [cd_tarefa]                                   VARCHAR (2)   NULL,
    [cd_despesa]                                  VARCHAR (2)   NULL,
    [vl_realizado]                                INT           NULL,
    [nr_recibo]                                   VARCHAR (9)   NULL,
    [ds_prazo_pagamento]                          VARCHAR (3)   NULL,
    [dt_realizado]                                DATE          NULL,
    [cd_cenario_prodesp]                          VARCHAR (140) NULL,
    [nr_ct]                                       VARCHAR (11)  NULL,
    [nr_empenho_siafem_siafisico]                 VARCHAR (11)  NULL,
    [cd_unidade_gestora]                          VARCHAR (6)   NULL,
    [cd_gestao]                                   VARCHAR (5)   NULL,
    [cd_nota_fiscal_prodesp]                      VARCHAR (6)   NULL,
    [nr_medicao]                                  VARCHAR (3)   NULL,
    [tb_natureza_tipo_id_natureza_tipo]           CHAR (1)      NULL,
    [vl_valor]                                    INT           NULL,
    [cd_evento]                                   INT           NULL,
    [dt_emissao]                                  DATE          NULL,
    [tb_evento_tipo_id_evento_tipo]               INT           NULL,
    [nr_cnpj_cpf_credor]                          VARCHAR (15)  NULL,
    [cd_gestao_credor]                            VARCHAR (140) NULL,
    [nr_ano_medicao]                              CHAR (4)      NULL,
    [nr_mes_medicao]                              CHAR (2)      NULL,
    [nr_percentual]                               VARCHAR (140) NULL,
    [tb_regional_id_regional]                     SMALLINT      NULL,
    [tb_programa_id_programa]                     INT           NULL,
    [tb_estrutura_id_estrutura]                   INT           NULL,
    [tb_fonte_id_fonte]                           INT           NULL,
    [cd_aplicacao_obra]                           VARCHAR (140) NULL,
    [tb_obra_tipo_id_obra_tipo]                   INT           NULL,
    [cd_unidade_gestora_obra]                     VARCHAR (6)   NULL,
    [cd_credor_organizacao]                       INT           NULL,
    [nr_cnpj_cpf_fornecedor]                      VARCHAR (15)  NULL,
    [ds_observacao_1]                             VARCHAR (76)  NULL,
    [ds_observacao_2]                             VARCHAR (76)  NULL,
    [ds_observacao_3]                             VARCHAR (76)  NULL,
    [nr_despesa_processo]                         VARCHAR (60)  NULL,
    [ds_nl_retencao_inss]                         VARCHAR (11)  NULL,
    [ds_lista]                                    VARCHAR (11)  NULL,
    [ds_despesa_referencia]                       VARCHAR (60)  NULL,
    [ds_despesa_autorizado_supra_folha]           CHAR (4)      NULL,
    [cd_despesa_especificacao_despesa]            CHAR (3)      NULL,
    [ds_despesa_especificacao_1]                  VARCHAR (79)  NULL,
    [ds_despesa_especificacao_2]                  VARCHAR (79)  NULL,
    [ds_despesa_especificacao_3]                  VARCHAR (79)  NULL,
    [ds_despesa_especificacao_4]                  VARCHAR (79)  NULL,
    [ds_despesa_especificacao_5]                  VARCHAR (79)  NULL,
    [ds_despesa_especificacao_6]                  VARCHAR (79)  NULL,
    [ds_despesa_especificacao_7]                  VARCHAR (79)  NULL,
    [ds_despesa_especificacao_8]                  VARCHAR (79)  NULL,
    [ds_despesa_especificacao_9]                  VARCHAR (79)  NULL,
    [cd_assinatura_autorizado]                    VARCHAR (5)   NULL,
    [cd_assinatura_autorizado_grupo]              INT           NULL,
    [cd_assinatura_autorizado_orgao]              CHAR (2)      NULL,
    [ds_assinatura_autorizado_cargo]              VARCHAR (55)  NULL,
    [nm_assinatura_autorizado]                    VARCHAR (55)  NULL,
    [cd_assinatura_examinado]                     VARCHAR (5)   NULL,
    [cd_assinatura_examinado_grupo]               INT           NULL,
    [cd_assinatura_examinado_orgao]               CHAR (2)      NULL,
    [ds_assinatura_examinado_cargo]               VARCHAR (55)  NULL,
    [nm_assinatura_examinado]                     VARCHAR (55)  NULL,
    [cd_assinatura_responsavel]                   VARCHAR (5)   NULL,
    [cd_assinatura_responsavel_grupo]             INT           NULL,
    [cd_assinatura_responsavel_orgao]             CHAR (2)      NULL,
    [ds_assinatura_responsavel_cargo]             VARCHAR (55)  NULL,
    [nm_assinatura_responsavel]                   VARCHAR (55)  NULL,
    [nr_caucao_guia]                              VARCHAR (6)   NULL,
    [nm_caucao_quota_geral_autorizado_por]        VARCHAR (35)  NULL,
    [vl_caucao_caucionado]                        INT           NULL,
    [cd_transmissao_status_prodesp]               CHAR (1)      CONSTRAINT [DF_tb_subempenho_cd_transmissao_status_prodesp] DEFAULT ('N') NULL,
    [fl_transmissao_transmitido_prodesp]          BIT           NULL,
    [dt_transmissao_transmitido_prodesp]          DATE          NULL,
    [ds_transmissao_mensagem_prodesp]             VARCHAR (140) NULL,
    [cd_transmissao_status_siafem_siafisico]      CHAR (1)      CONSTRAINT [DF_tb_subempenho_cd_transmissao_status_siafem_siafisico] DEFAULT ('N') NULL,
    [fl_transmissao_transmitido_siafem_siafisico] BIT           NULL,
    [dt_transmissao_transmitido_siafem_siafisico] DATE          NULL,
    [ds_transmissao_mensagem_siafem_siafisico]    VARCHAR (140) NULL,
    [fl_documento_completo]                       BIT           NULL,
    [fl_documento_status]                         BIT           NULL,
    [nr_obra]                                     VARCHAR (9)   NULL,
    [fl_sistema_siafisico]                        BIT           NULL,
    [cd_transmissao_status_siafisico]             CHAR (1)      NULL,
    [fl_transmissao_transmitido_siafisico]        BIT           NULL,
    [cd_obra_tipo]                                CHAR (1)      NULL,
    [nm_credor]                                   VARCHAR (14)  NULL,
    [dt_vencimento]                               DATE          NULL,
    [fl_referencia_digitada]                      BIT           NULL,
    CONSTRAINT [PK_tb_subempenho] PRIMARY KEY CLUSTERED ([id_subempenho] ASC),
    CONSTRAINT [CK_tb_subempenho_cd_transmissao_status_prodesp] CHECK ([cd_transmissao_status_prodesp]='N' OR [cd_transmissao_status_prodesp]='E' OR [cd_transmissao_status_prodesp]='S'),
    CONSTRAINT [CK_tb_subempenho_cd_transmissao_status_siafem_siafisico] CHECK ([cd_transmissao_status_siafem_siafisico]='N' OR [cd_transmissao_status_siafem_siafisico]='E' OR [cd_transmissao_status_siafem_siafisico]='S'),
    CONSTRAINT [FK_tb_subempenho_tb_cenario_tipo] FOREIGN KEY ([tb_cenario_id_cenario]) REFERENCES [pagamento].[tb_cenario_tipo] ([id_cenario_tipo]),
    CONSTRAINT [FK_tb_subempenho_tb_estrutura] FOREIGN KEY ([tb_estrutura_id_estrutura]) REFERENCES [configuracao].[tb_estrutura] ([id_estrutura]),
    CONSTRAINT [FK_tb_subempenho_tb_evento_tipo] FOREIGN KEY ([tb_evento_tipo_id_evento_tipo]) REFERENCES [pagamento].[tb_evento_tipo] ([id_evento_tipo]),
    CONSTRAINT [FK_tb_subempenho_tb_fonte] FOREIGN KEY ([tb_fonte_id_fonte]) REFERENCES [configuracao].[tb_fonte] ([id_fonte]),
    CONSTRAINT [FK_tb_subempenho_tb_natureza_tipo] FOREIGN KEY ([tb_natureza_tipo_id_natureza_tipo]) REFERENCES [pagamento].[tb_natureza_tipo] ([id_natureza_tipo]),
    CONSTRAINT [FK_tb_subempenho_tb_obra_tipo] FOREIGN KEY ([tb_obra_tipo_id_obra_tipo]) REFERENCES [pagamento].[tb_obra_tipo] ([id_obra_tipo]),
    CONSTRAINT [FK_tb_subempenho_tb_programa] FOREIGN KEY ([tb_programa_id_programa]) REFERENCES [configuracao].[tb_programa] ([id_programa]),
    CONSTRAINT [FK_tb_subempenho_tb_regional] FOREIGN KEY ([tb_regional_id_regional]) REFERENCES [seguranca].[tb_regional] ([id_regional])
);



