CREATE TABLE [pagamento].[tb_subempenho_cancelamento] (
    [id_subempenho_cancelamento]                  INT           IDENTITY (1, 1) NOT NULL,
    [dt_cadastro]                                 DATE          NULL,
    [fl_sistema_prodesp]                          BIT           NULL,
    [fl_sistema_siafem_siafisico]                 BIT           NULL,
    [nr_prodesp]                                  VARCHAR (17)  NULL,
    [nr_siafem_siafisico]                         VARCHAR (11)  NULL,
    [nr_contrato]                                 VARCHAR (13)  NULL,
    [tb_cenario_id_cenario]                       INT           NULL,
    [nr_subempenho_prodesp]                       VARCHAR (13)  NULL,
    [vl_realizado]                                INT           NULL,
    [cd_cenario_prodesp]                          VARCHAR (140) NULL,
    [nr_ct]                                       VARCHAR (11)  NULL,
    [nr_nl_referencia]                            VARCHAR (11)  NULL,
    [nr_empenho_siafem_siafisico]                 VARCHAR (11)  NULL,
    [cd_unidade_gestora]                          VARCHAR (6)   NULL,
    [cd_gestao]                                   VARCHAR (5)   NULL,
    [vl_valor]                                    INT           NULL,
    [dt_emissao]                                  DATE          NULL,
    [tb_evento_tipo_id_evento_tipo]               INT           NULL,
    [nr_cnpj_cpf_credor]                          VARCHAR (15)  NULL,
    [cd_gestao_credor]                            VARCHAR (140) NULL,
    [nr_ano_medicao]                              CHAR (4)      NULL,
    [nr_mes_medicao]                              CHAR (2)      NULL,
    [nr_percentual]                               VARCHAR (140) NULL,
    [cd_classificacao_despesa]                    VARCHAR (140) NULL,
    [tb_regional_id_regional]                     SMALLINT      NULL,
    [cd_aplicacao_obra]                           VARCHAR (140) NULL,
    [tb_obra_tipo_id_obra_tipo]                   INT           NULL,
    [cd_obra_tipo]                                CHAR (1)      NULL,
    [nr_obra]                                     VARCHAR (9)   NULL,
    [cd_unidade_gestora_obra]                     VARCHAR (6)   NULL,
    [ds_observacao_1]                             VARCHAR (76)  NULL,
    [ds_observacao_2]                             VARCHAR (76)  NULL,
    [ds_observacao_3]                             VARCHAR (76)  NULL,
    [nr_despesa_processo]                         VARCHAR (60)  NULL,
    [ds_despesa_referencia]                       VARCHAR (60)  NULL,
    [ds_despesa_autorizado_supra_folha]           CHAR (4)      NULL,
    [cd_despesa_especificacao_despesa]            CHAR (3)      NULL,
    [ds_despesa_especificacao_1]                  VARCHAR (79)  NULL,
    [ds_despesa_especificacao_2]                  VARCHAR (79)  NULL,
    [ds_despesa_especificacao_3]                  VARCHAR (79)  NULL,
    [ds_despesa_especificacao_4]                  VARCHAR (79)  NULL,
    [ds_despesa_especificacao_5]                  VARCHAR (79)  NULL,
    [ds_despesa_especificacao_6]                  VARCHAR (79)  NULL,
    [ds_despesa_especificacao_7]                  VARCHAR (79)  NULL,
    [ds_despesa_especificacao_8]                  VARCHAR (79)  NULL,
    [ds_despesa_especificacao_9]                  VARCHAR (79)  NULL,
    [cd_assinatura_autorizado]                    VARCHAR (5)   NULL,
    [cd_assinatura_autorizado_grupo]              INT           NULL,
    [cd_assinatura_autorizado_orgao]              CHAR (2)      NULL,
    [ds_assinatura_autorizado_cargo]              VARCHAR (55)  NULL,
    [nm_assinatura_autorizado]                    VARCHAR (55)  NULL,
    [cd_assinatura_examinado]                     VARCHAR (5)   NULL,
    [cd_assinatura_examinado_grupo]               INT           NULL,
    [cd_assinatura_examinado_orgao]               CHAR (2)      NULL,
    [ds_assinatura_examinado_cargo]               VARCHAR (55)  NULL,
    [nm_assinatura_examinado]                     VARCHAR (55)  NULL,
    [cd_assinatura_responsavel]                   VARCHAR (5)   NULL,
    [cd_assinatura_responsavel_grupo]             INT           NULL,
    [cd_assinatura_responsavel_orgao]             CHAR (2)      NULL,
    [ds_assinatura_responsavel_cargo]             VARCHAR (55)  NULL,
    [nm_assinatura_responsavel]                   VARCHAR (55)  NULL,
    [cd_transmissao_status_prodesp]               CHAR (1)      NULL,
    [fl_transmissao_transmitido_prodesp]          BIT           NULL,
    [dt_transmissao_transmitido_prodesp]          DATE          NULL,
    [ds_transmissao_mensagem_prodesp]             VARCHAR (140) NULL,
    [cd_transmissao_status_siafem_siafisico]      CHAR (1)      NULL,
    [fl_transmissao_transmitido_siafem_siafisico] BIT           NULL,
    [dt_transmissao_transmitido_siafem_siafisico] DATE          NULL,
    [ds_transmissao_mensagem_siafem_siafisico]    VARCHAR (140) NULL,
    [fl_documento_completo]                       BIT           NULL,
    [fl_documento_status]                         BIT           NULL,
    [fl_sistema_siafisico]                        BIT           NULL,
    [cd_transmissao_status_siafisico]             CHAR (1)      NULL,
    [fl_transmissao_transmitido_siafisico]        BIT           NULL,
    [vl_anular]                                   INT           NULL,
    [cd_evento]                                   INT           NULL,
    CONSTRAINT [PK_tb_subempenho_cancelamento] PRIMARY KEY CLUSTERED ([id_subempenho_cancelamento] ASC),
    CONSTRAINT [FK_tb_subempenho_cancelamento_tb_cenario_tipo] FOREIGN KEY ([tb_cenario_id_cenario]) REFERENCES [pagamento].[tb_cenario_tipo] ([id_cenario_tipo]),
    CONSTRAINT [FK_tb_subempenho_cancelamento_tb_evento_tipo] FOREIGN KEY ([tb_evento_tipo_id_evento_tipo]) REFERENCES [pagamento].[tb_evento_tipo] ([id_evento_tipo]),
    CONSTRAINT [FK_tb_subempenho_cancelamento_tb_obra_tipo] FOREIGN KEY ([tb_obra_tipo_id_obra_tipo]) REFERENCES [pagamento].[tb_obra_tipo] ([id_obra_tipo]),
    CONSTRAINT [FK_tb_subempenho_cancelamento_tb_regional] FOREIGN KEY ([tb_regional_id_regional]) REFERENCES [seguranca].[tb_regional] ([id_regional])
);



