//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Sids.Prodesp.Infrastructure.ProdespEmpenho {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Integracao_DER_SIAFEM_EmpenhoPortBinding", Namespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho")]
    public partial class Integracao_DER_SIAFEM_EmpenhoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Procedure_AnulacaoEmpenhoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Procedure_ConsultaEmpenhoEstruturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Procedure_InclusaoEmpenhoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Procedure_ReforcoEmpenhoOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsResourceCreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback wsResourceDestroyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Integracao_DER_SIAFEM_EmpenhoService() {
            this.Url = global::Sids.Prodesp.Infrastructure.Properties.Settings.Default.Sids_Prodesp_Prodesp_Empenho_Desevolvomento;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Procedure_AnulacaoEmpenhoCompletedEventHandler Procedure_AnulacaoEmpenhoCompleted;
        
        /// <remarks/>
        public event Procedure_ConsultaEmpenhoEstruturaCompletedEventHandler Procedure_ConsultaEmpenhoEstruturaCompleted;
        
        /// <remarks/>
        public event Procedure_InclusaoEmpenhoCompletedEventHandler Procedure_InclusaoEmpenhoCompleted;
        
        /// <remarks/>
        public event Procedure_ReforcoEmpenhoCompletedEventHandler Procedure_ReforcoEmpenhoCompleted;
        
        /// <remarks/>
        public event wsResourceCreateCompletedEventHandler wsResourceCreateCompleted;
        
        /// <remarks/>
        public event wsResourceDestroyCompletedEventHandler wsResourceDestroyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho", ResponseNamespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Procedure_AnulacaoEmpenhoRecord")]
        public Procedure_AnulacaoEmpenhoRecordType[] Procedure_AnulacaoEmpenho(Procedure_AnulacaoEmpenhoFiltersType Procedure_AnulacaoEmpenhoFilters, ModelVariablesType ModelVariables, EnvironmentVariablesType EnvironmentVariables) {
            object[] results = this.Invoke("Procedure_AnulacaoEmpenho", new object[] {
                        Procedure_AnulacaoEmpenhoFilters,
                        ModelVariables,
                        EnvironmentVariables});
            return ((Procedure_AnulacaoEmpenhoRecordType[])(results[0]));
        }
        
        /// <remarks/>
        public void Procedure_AnulacaoEmpenhoAsync(Procedure_AnulacaoEmpenhoFiltersType Procedure_AnulacaoEmpenhoFilters, ModelVariablesType ModelVariables, EnvironmentVariablesType EnvironmentVariables) {
            this.Procedure_AnulacaoEmpenhoAsync(Procedure_AnulacaoEmpenhoFilters, ModelVariables, EnvironmentVariables, null);
        }
        
        /// <remarks/>
        public void Procedure_AnulacaoEmpenhoAsync(Procedure_AnulacaoEmpenhoFiltersType Procedure_AnulacaoEmpenhoFilters, ModelVariablesType ModelVariables, EnvironmentVariablesType EnvironmentVariables, object userState) {
            if ((this.Procedure_AnulacaoEmpenhoOperationCompleted == null)) {
                this.Procedure_AnulacaoEmpenhoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcedure_AnulacaoEmpenhoOperationCompleted);
            }
            this.InvokeAsync("Procedure_AnulacaoEmpenho", new object[] {
                        Procedure_AnulacaoEmpenhoFilters,
                        ModelVariables,
                        EnvironmentVariables}, this.Procedure_AnulacaoEmpenhoOperationCompleted, userState);
        }
        
        private void OnProcedure_AnulacaoEmpenhoOperationCompleted(object arg) {
            if ((this.Procedure_AnulacaoEmpenhoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Procedure_AnulacaoEmpenhoCompleted(this, new Procedure_AnulacaoEmpenhoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho", ResponseNamespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Procedure_ConsultaEmpenhoEstruturaRecord")]
        public Procedure_ConsultaEmpenhoEstruturaRecordType[] Procedure_ConsultaEmpenhoEstrutura(Procedure_ConsultaEmpenhoEstruturaFiltersType Procedure_ConsultaEmpenhoEstruturaFilters, ModelVariablesType ModelVariables, EnvironmentVariablesType EnvironmentVariables) {
            object[] results = this.Invoke("Procedure_ConsultaEmpenhoEstrutura", new object[] {
                        Procedure_ConsultaEmpenhoEstruturaFilters,
                        ModelVariables,
                        EnvironmentVariables});
            return ((Procedure_ConsultaEmpenhoEstruturaRecordType[])(results[0]));
        }
        
        /// <remarks/>
        public void Procedure_ConsultaEmpenhoEstruturaAsync(Procedure_ConsultaEmpenhoEstruturaFiltersType Procedure_ConsultaEmpenhoEstruturaFilters, ModelVariablesType ModelVariables, EnvironmentVariablesType EnvironmentVariables) {
            this.Procedure_ConsultaEmpenhoEstruturaAsync(Procedure_ConsultaEmpenhoEstruturaFilters, ModelVariables, EnvironmentVariables, null);
        }
        
        /// <remarks/>
        public void Procedure_ConsultaEmpenhoEstruturaAsync(Procedure_ConsultaEmpenhoEstruturaFiltersType Procedure_ConsultaEmpenhoEstruturaFilters, ModelVariablesType ModelVariables, EnvironmentVariablesType EnvironmentVariables, object userState) {
            if ((this.Procedure_ConsultaEmpenhoEstruturaOperationCompleted == null)) {
                this.Procedure_ConsultaEmpenhoEstruturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcedure_ConsultaEmpenhoEstruturaOperationCompleted);
            }
            this.InvokeAsync("Procedure_ConsultaEmpenhoEstrutura", new object[] {
                        Procedure_ConsultaEmpenhoEstruturaFilters,
                        ModelVariables,
                        EnvironmentVariables}, this.Procedure_ConsultaEmpenhoEstruturaOperationCompleted, userState);
        }
        
        private void OnProcedure_ConsultaEmpenhoEstruturaOperationCompleted(object arg) {
            if ((this.Procedure_ConsultaEmpenhoEstruturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Procedure_ConsultaEmpenhoEstruturaCompleted(this, new Procedure_ConsultaEmpenhoEstruturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho", ResponseNamespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Procedure_InclusaoEmpenhoRecord")]
        public Procedure_InclusaoEmpenhoRecordType[] Procedure_InclusaoEmpenho(Procedure_InclusaoEmpenhoFiltersType Procedure_InclusaoEmpenhoFilters, ModelVariablesType ModelVariables, EnvironmentVariablesType EnvironmentVariables) {
            object[] results = this.Invoke("Procedure_InclusaoEmpenho", new object[] {
                        Procedure_InclusaoEmpenhoFilters,
                        ModelVariables,
                        EnvironmentVariables});
            return ((Procedure_InclusaoEmpenhoRecordType[])(results[0]));
        }
        
        /// <remarks/>
        public void Procedure_InclusaoEmpenhoAsync(Procedure_InclusaoEmpenhoFiltersType Procedure_InclusaoEmpenhoFilters, ModelVariablesType ModelVariables, EnvironmentVariablesType EnvironmentVariables) {
            this.Procedure_InclusaoEmpenhoAsync(Procedure_InclusaoEmpenhoFilters, ModelVariables, EnvironmentVariables, null);
        }
        
        /// <remarks/>
        public void Procedure_InclusaoEmpenhoAsync(Procedure_InclusaoEmpenhoFiltersType Procedure_InclusaoEmpenhoFilters, ModelVariablesType ModelVariables, EnvironmentVariablesType EnvironmentVariables, object userState) {
            if ((this.Procedure_InclusaoEmpenhoOperationCompleted == null)) {
                this.Procedure_InclusaoEmpenhoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcedure_InclusaoEmpenhoOperationCompleted);
            }
            this.InvokeAsync("Procedure_InclusaoEmpenho", new object[] {
                        Procedure_InclusaoEmpenhoFilters,
                        ModelVariables,
                        EnvironmentVariables}, this.Procedure_InclusaoEmpenhoOperationCompleted, userState);
        }
        
        private void OnProcedure_InclusaoEmpenhoOperationCompleted(object arg) {
            if ((this.Procedure_InclusaoEmpenhoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Procedure_InclusaoEmpenhoCompleted(this, new Procedure_InclusaoEmpenhoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho", ResponseNamespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Procedure_ReforcoEmpenhoRecord")]
        public Procedure_ReforcoEmpenhoRecordType[] Procedure_ReforcoEmpenho(Procedure_ReforcoEmpenhoFiltersType Procedure_ReforcoEmpenhoFilters, ModelVariablesType ModelVariables, EnvironmentVariablesType EnvironmentVariables) {
            object[] results = this.Invoke("Procedure_ReforcoEmpenho", new object[] {
                        Procedure_ReforcoEmpenhoFilters,
                        ModelVariables,
                        EnvironmentVariables});
            return ((Procedure_ReforcoEmpenhoRecordType[])(results[0]));
        }
        
        /// <remarks/>
        public void Procedure_ReforcoEmpenhoAsync(Procedure_ReforcoEmpenhoFiltersType Procedure_ReforcoEmpenhoFilters, ModelVariablesType ModelVariables, EnvironmentVariablesType EnvironmentVariables) {
            this.Procedure_ReforcoEmpenhoAsync(Procedure_ReforcoEmpenhoFilters, ModelVariables, EnvironmentVariables, null);
        }
        
        /// <remarks/>
        public void Procedure_ReforcoEmpenhoAsync(Procedure_ReforcoEmpenhoFiltersType Procedure_ReforcoEmpenhoFilters, ModelVariablesType ModelVariables, EnvironmentVariablesType EnvironmentVariables, object userState) {
            if ((this.Procedure_ReforcoEmpenhoOperationCompleted == null)) {
                this.Procedure_ReforcoEmpenhoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcedure_ReforcoEmpenhoOperationCompleted);
            }
            this.InvokeAsync("Procedure_ReforcoEmpenho", new object[] {
                        Procedure_ReforcoEmpenhoFilters,
                        ModelVariables,
                        EnvironmentVariables}, this.Procedure_ReforcoEmpenhoOperationCompleted, userState);
        }
        
        private void OnProcedure_ReforcoEmpenhoOperationCompleted(object arg) {
            if ((this.Procedure_ReforcoEmpenhoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Procedure_ReforcoEmpenhoCompleted(this, new Procedure_ReforcoEmpenhoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho", ResponseNamespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SessionId")]
        public string wsResourceCreate(ModelVariablesType ModelVariables, EnvironmentVariablesType EnvironmentVariables) {
            object[] results = this.Invoke("wsResourceCreate", new object[] {
                        ModelVariables,
                        EnvironmentVariables});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wsResourceCreateAsync(ModelVariablesType ModelVariables, EnvironmentVariablesType EnvironmentVariables) {
            this.wsResourceCreateAsync(ModelVariables, EnvironmentVariables, null);
        }
        
        /// <remarks/>
        public void wsResourceCreateAsync(ModelVariablesType ModelVariables, EnvironmentVariablesType EnvironmentVariables, object userState) {
            if ((this.wsResourceCreateOperationCompleted == null)) {
                this.wsResourceCreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsResourceCreateOperationCompleted);
            }
            this.InvokeAsync("wsResourceCreate", new object[] {
                        ModelVariables,
                        EnvironmentVariables}, this.wsResourceCreateOperationCompleted, userState);
        }
        
        private void OnwsResourceCreateOperationCompleted(object arg) {
            if ((this.wsResourceCreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsResourceCreateCompleted(this, new wsResourceCreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho", ResponseNamespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void wsResourceDestroy(EnvironmentVariablesType EnvironmentVariables) {
            this.Invoke("wsResourceDestroy", new object[] {
                        EnvironmentVariables});
        }
        
        /// <remarks/>
        public void wsResourceDestroyAsync(EnvironmentVariablesType EnvironmentVariables) {
            this.wsResourceDestroyAsync(EnvironmentVariables, null);
        }
        
        /// <remarks/>
        public void wsResourceDestroyAsync(EnvironmentVariablesType EnvironmentVariables, object userState) {
            if ((this.wsResourceDestroyOperationCompleted == null)) {
                this.wsResourceDestroyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsResourceDestroyOperationCompleted);
            }
            this.InvokeAsync("wsResourceDestroy", new object[] {
                        EnvironmentVariables}, this.wsResourceDestroyOperationCompleted, userState);
        }
        
        private void OnwsResourceDestroyOperationCompleted(object arg) {
            if ((this.wsResourceDestroyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsResourceDestroyCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho")]
    public partial class Procedure_AnulacaoEmpenhoFiltersType {
        
        private string inChaveField;
        
        private string inImpressoraField;
        
        private string inOperadorField;
        
        private string inEmpenhoField;
        
        private string inQuota1Field;
        
        private string inQuota2Field;
        
        private string inQuota3Field;
        
        private string inQuota4Field;
        
        private string inTotalField;
        
        private string inAutFLSField;
        
        private string inCodAssinAutorizacaoField;
        
        private string inCodAssinExaminadoField;
        
        private string inCodAssinResponsField;
        
        private string inCodEspecificaDespField;
        
        private string inDestinoRecursoField;
        
        private string inGrupoAssinAutorizacaoField;
        
        private string inGrupoAssinExaminadoField;
        
        private string inGrupoAssinResponsField;
        
        private string inNumProcessoField;
        
        private string inOrgaoAssinAutorizacaoField;
        
        private string inOrgaoAssinExaminadoField;
        
        private string inOrgaoAssinResponsField;
        
        private string inOrigemRecursoField;
        
        private string inEspecificaDesp_01Field;
        
        private string inEspecificaDesp_02Field;
        
        private string inEspecificaDesp_03Field;
        
        private string inEspecificaDesp_04Field;
        
        private string inEspecificaDesp_05Field;
        
        private string inEspecificaDesp_06Field;
        
        private string inEspecificaDesp_07Field;
        
        private string inEspecificaDesp_08Field;
        
        private string inEspecificaDesp_09Field;
        
        private string inImprimirField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inChave {
            get {
                return this.inChaveField;
            }
            set {
                this.inChaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inImpressora {
            get {
                return this.inImpressoraField;
            }
            set {
                this.inImpressoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inOperador {
            get {
                return this.inOperadorField;
            }
            set {
                this.inOperadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEmpenho {
            get {
                return this.inEmpenhoField;
            }
            set {
                this.inEmpenhoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inQuota1 {
            get {
                return this.inQuota1Field;
            }
            set {
                this.inQuota1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inQuota2 {
            get {
                return this.inQuota2Field;
            }
            set {
                this.inQuota2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inQuota3 {
            get {
                return this.inQuota3Field;
            }
            set {
                this.inQuota3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inQuota4 {
            get {
                return this.inQuota4Field;
            }
            set {
                this.inQuota4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inTotal {
            get {
                return this.inTotalField;
            }
            set {
                this.inTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inAutFLS {
            get {
                return this.inAutFLSField;
            }
            set {
                this.inAutFLSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCodAssinAutorizacao {
            get {
                return this.inCodAssinAutorizacaoField;
            }
            set {
                this.inCodAssinAutorizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCodAssinExaminado {
            get {
                return this.inCodAssinExaminadoField;
            }
            set {
                this.inCodAssinExaminadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCodAssinRespons {
            get {
                return this.inCodAssinResponsField;
            }
            set {
                this.inCodAssinResponsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCodEspecificaDesp {
            get {
                return this.inCodEspecificaDespField;
            }
            set {
                this.inCodEspecificaDespField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inDestinoRecurso {
            get {
                return this.inDestinoRecursoField;
            }
            set {
                this.inDestinoRecursoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inGrupoAssinAutorizacao {
            get {
                return this.inGrupoAssinAutorizacaoField;
            }
            set {
                this.inGrupoAssinAutorizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inGrupoAssinExaminado {
            get {
                return this.inGrupoAssinExaminadoField;
            }
            set {
                this.inGrupoAssinExaminadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inGrupoAssinRespons {
            get {
                return this.inGrupoAssinResponsField;
            }
            set {
                this.inGrupoAssinResponsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inNumProcesso {
            get {
                return this.inNumProcessoField;
            }
            set {
                this.inNumProcessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inOrgaoAssinAutorizacao {
            get {
                return this.inOrgaoAssinAutorizacaoField;
            }
            set {
                this.inOrgaoAssinAutorizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inOrgaoAssinExaminado {
            get {
                return this.inOrgaoAssinExaminadoField;
            }
            set {
                this.inOrgaoAssinExaminadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InOrgaoAssinRespons {
            get {
                return this.inOrgaoAssinResponsField;
            }
            set {
                this.inOrgaoAssinResponsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inOrigemRecurso {
            get {
                return this.inOrigemRecursoField;
            }
            set {
                this.inOrigemRecursoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_01 {
            get {
                return this.inEspecificaDesp_01Field;
            }
            set {
                this.inEspecificaDesp_01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_02 {
            get {
                return this.inEspecificaDesp_02Field;
            }
            set {
                this.inEspecificaDesp_02Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_03 {
            get {
                return this.inEspecificaDesp_03Field;
            }
            set {
                this.inEspecificaDesp_03Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_04 {
            get {
                return this.inEspecificaDesp_04Field;
            }
            set {
                this.inEspecificaDesp_04Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_05 {
            get {
                return this.inEspecificaDesp_05Field;
            }
            set {
                this.inEspecificaDesp_05Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_06 {
            get {
                return this.inEspecificaDesp_06Field;
            }
            set {
                this.inEspecificaDesp_06Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_07 {
            get {
                return this.inEspecificaDesp_07Field;
            }
            set {
                this.inEspecificaDesp_07Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_08 {
            get {
                return this.inEspecificaDesp_08Field;
            }
            set {
                this.inEspecificaDesp_08Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_09 {
            get {
                return this.inEspecificaDesp_09Field;
            }
            set {
                this.inEspecificaDesp_09Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inImprimir {
            get {
                return this.inImprimirField;
            }
            set {
                this.inImprimirField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho")]
    public partial class Procedure_ReforcoEmpenhoRecordType {
        
        private string outTerminalField;
        
        private string outCidadeCredorField;
        
        private string outCredor1Field;
        
        private string outCredor2Field;
        
        private string outEnderecoCredorField;
        
        private string outEstadoCredorField;
        
        private string outNumReforcoEmpField;
        
        private string outSucessoField;
        
        private string outTipoDocField;
        
        private string outErroField;
        
        /// <remarks/>
        public string outTerminal {
            get {
                return this.outTerminalField;
            }
            set {
                this.outTerminalField = value;
            }
        }
        
        /// <remarks/>
        public string outCidadeCredor {
            get {
                return this.outCidadeCredorField;
            }
            set {
                this.outCidadeCredorField = value;
            }
        }
        
        /// <remarks/>
        public string outCredor1 {
            get {
                return this.outCredor1Field;
            }
            set {
                this.outCredor1Field = value;
            }
        }
        
        /// <remarks/>
        public string outCredor2 {
            get {
                return this.outCredor2Field;
            }
            set {
                this.outCredor2Field = value;
            }
        }
        
        /// <remarks/>
        public string outEnderecoCredor {
            get {
                return this.outEnderecoCredorField;
            }
            set {
                this.outEnderecoCredorField = value;
            }
        }
        
        /// <remarks/>
        public string outEstadoCredor {
            get {
                return this.outEstadoCredorField;
            }
            set {
                this.outEstadoCredorField = value;
            }
        }
        
        /// <remarks/>
        public string outNumReforcoEmp {
            get {
                return this.outNumReforcoEmpField;
            }
            set {
                this.outNumReforcoEmpField = value;
            }
        }
        
        /// <remarks/>
        public string outSucesso {
            get {
                return this.outSucessoField;
            }
            set {
                this.outSucessoField = value;
            }
        }
        
        /// <remarks/>
        public string outTipoDoc {
            get {
                return this.outTipoDocField;
            }
            set {
                this.outTipoDocField = value;
            }
        }
        
        /// <remarks/>
        public string outErro {
            get {
                return this.outErroField;
            }
            set {
                this.outErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho")]
    public partial class Procedure_ReforcoEmpenhoFiltersType {
        
        private string inChaveField;
        
        private string inImpressoraField;
        
        private string inOperadorField;
        
        private string inEmpenhoField;
        
        private string inQuota1Field;
        
        private string inQuota2Field;
        
        private string inQuota3Field;
        
        private string inQuota4Field;
        
        private string inReforcoSIAFEMField;
        
        private string inReservaField;
        
        private string inTotalField;
        
        private string inAutFLSField;
        
        private string inCodAssinAutorizacaoField;
        
        private string inCodAssinExaminadoField;
        
        private string inCodAssinResponsField;
        
        private string inCodEspecificaDespField;
        
        private string inDestinoRecursoField;
        
        private string inGrupoAssinAutorizacaoField;
        
        private string inGrupoAssinExaminadoField;
        
        private string inGrupoAssinResponsField;
        
        private string inNumProcessoField;
        
        private string inOrgaoAssinAutorizacaoField;
        
        private string inOrgaoAssinExaminadoField;
        
        private string inOrgaoAssinResponsField;
        
        private string inOrigemRecursoField;
        
        private string inEspecificaDesp_01Field;
        
        private string inEspecificaDesp_02Field;
        
        private string inEspecificaDesp_03Field;
        
        private string inEspecificaDesp_04Field;
        
        private string inEspecificaDesp_05Field;
        
        private string inEspecificaDesp_06Field;
        
        private string inEspecificaDesp_07Field;
        
        private string inEspecificaDesp_08Field;
        
        private string inEspecificaDesp_09Field;
        
        private string inImprimirField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inChave {
            get {
                return this.inChaveField;
            }
            set {
                this.inChaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inImpressora {
            get {
                return this.inImpressoraField;
            }
            set {
                this.inImpressoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inOperador {
            get {
                return this.inOperadorField;
            }
            set {
                this.inOperadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEmpenho {
            get {
                return this.inEmpenhoField;
            }
            set {
                this.inEmpenhoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inQuota1 {
            get {
                return this.inQuota1Field;
            }
            set {
                this.inQuota1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inQuota2 {
            get {
                return this.inQuota2Field;
            }
            set {
                this.inQuota2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inQuota3 {
            get {
                return this.inQuota3Field;
            }
            set {
                this.inQuota3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inQuota4 {
            get {
                return this.inQuota4Field;
            }
            set {
                this.inQuota4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inReforcoSIAFEM {
            get {
                return this.inReforcoSIAFEMField;
            }
            set {
                this.inReforcoSIAFEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inReserva {
            get {
                return this.inReservaField;
            }
            set {
                this.inReservaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inTotal {
            get {
                return this.inTotalField;
            }
            set {
                this.inTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inAutFLS {
            get {
                return this.inAutFLSField;
            }
            set {
                this.inAutFLSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCodAssinAutorizacao {
            get {
                return this.inCodAssinAutorizacaoField;
            }
            set {
                this.inCodAssinAutorizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCodAssinExaminado {
            get {
                return this.inCodAssinExaminadoField;
            }
            set {
                this.inCodAssinExaminadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCodAssinRespons {
            get {
                return this.inCodAssinResponsField;
            }
            set {
                this.inCodAssinResponsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCodEspecificaDesp {
            get {
                return this.inCodEspecificaDespField;
            }
            set {
                this.inCodEspecificaDespField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inDestinoRecurso {
            get {
                return this.inDestinoRecursoField;
            }
            set {
                this.inDestinoRecursoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inGrupoAssinAutorizacao {
            get {
                return this.inGrupoAssinAutorizacaoField;
            }
            set {
                this.inGrupoAssinAutorizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inGrupoAssinExaminado {
            get {
                return this.inGrupoAssinExaminadoField;
            }
            set {
                this.inGrupoAssinExaminadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inGrupoAssinRespons {
            get {
                return this.inGrupoAssinResponsField;
            }
            set {
                this.inGrupoAssinResponsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inNumProcesso {
            get {
                return this.inNumProcessoField;
            }
            set {
                this.inNumProcessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inOrgaoAssinAutorizacao {
            get {
                return this.inOrgaoAssinAutorizacaoField;
            }
            set {
                this.inOrgaoAssinAutorizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inOrgaoAssinExaminado {
            get {
                return this.inOrgaoAssinExaminadoField;
            }
            set {
                this.inOrgaoAssinExaminadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InOrgaoAssinRespons {
            get {
                return this.inOrgaoAssinResponsField;
            }
            set {
                this.inOrgaoAssinResponsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inOrigemRecurso {
            get {
                return this.inOrigemRecursoField;
            }
            set {
                this.inOrigemRecursoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_01 {
            get {
                return this.inEspecificaDesp_01Field;
            }
            set {
                this.inEspecificaDesp_01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_02 {
            get {
                return this.inEspecificaDesp_02Field;
            }
            set {
                this.inEspecificaDesp_02Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_03 {
            get {
                return this.inEspecificaDesp_03Field;
            }
            set {
                this.inEspecificaDesp_03Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_04 {
            get {
                return this.inEspecificaDesp_04Field;
            }
            set {
                this.inEspecificaDesp_04Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_05 {
            get {
                return this.inEspecificaDesp_05Field;
            }
            set {
                this.inEspecificaDesp_05Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_06 {
            get {
                return this.inEspecificaDesp_06Field;
            }
            set {
                this.inEspecificaDesp_06Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_07 {
            get {
                return this.inEspecificaDesp_07Field;
            }
            set {
                this.inEspecificaDesp_07Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_08 {
            get {
                return this.inEspecificaDesp_08Field;
            }
            set {
                this.inEspecificaDesp_08Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_09 {
            get {
                return this.inEspecificaDesp_09Field;
            }
            set {
                this.inEspecificaDesp_09Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inImprimir {
            get {
                return this.inImprimirField;
            }
            set {
                this.inImprimirField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho")]
    public partial class Procedure_InclusaoEmpenhoRecordType {
        
        private string outTerminalField;
        
        private string outNumEmpenhoField;
        
        private string outSucessoField;
        
        private string outTipoDocField;
        
        private string outErroField;
        
        /// <remarks/>
        public string outTerminal {
            get {
                return this.outTerminalField;
            }
            set {
                this.outTerminalField = value;
            }
        }
        
        /// <remarks/>
        public string outNumEmpenho {
            get {
                return this.outNumEmpenhoField;
            }
            set {
                this.outNumEmpenhoField = value;
            }
        }
        
        /// <remarks/>
        public string outSucesso {
            get {
                return this.outSucessoField;
            }
            set {
                this.outSucessoField = value;
            }
        }
        
        /// <remarks/>
        public string outTipoDoc {
            get {
                return this.outTipoDocField;
            }
            set {
                this.outTipoDocField = value;
            }
        }
        
        /// <remarks/>
        public string outErro {
            get {
                return this.outErroField;
            }
            set {
                this.outErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho")]
    public partial class Procedure_InclusaoEmpenhoFiltersType {
        
        private string inChaveField;
        
        private string inImpressoraField;
        
        private string inOperadorField;
        
        private string inAplicacaoField;
        
        private string inCEDField;
        
        private string inCFPField;
        
        private string inCGC_CPFField;
        
        private string inCodNaturItemField;
        
        private string inContratoANOField;
        
        private string inContratoDCField;
        
        private string inContratoNUMField;
        
        private string inContratoORGAOField;
        
        private string inCredorOrganTipoField;
        
        private string inExerField;
        
        private string inNumNEField;
        
        private string inOrgaoField;
        
        private string inQuota1Field;
        
        private string inQuota2Field;
        
        private string inQuota3Field;
        
        private string inQuota4Field;
        
        private string inReservaField;
        
        private string inTipoEmpenhoField;
        
        private string inTotalField;
        
        private string inAutFLSField;
        
        private string inCodAssinAutorizacaoField;
        
        private string inCodAssinExaminadoField;
        
        private string inCodAssinResponsField;
        
        private string inCodEspecificaDespField;
        
        private string inDestinoRecursoField;
        
        private string inFonteNEField;
        
        private string inGrupoAssinAutorizacaoField;
        
        private string inGrupoAssinExaminadoField;
        
        private string inGrupoAssinResponsField;
        
        private string inNumProcessoField;
        
        private string inOrgaoAssinAutorizacaoField;
        
        private string inOrgaoAssinExaminadoField;
        
        private string inOrgaoAssinResponsField;
        
        private string inOrigemRecursoField;
        
        private string inProcessoNEField;
        
        private string inEspecificaDesp_01Field;
        
        private string inEspecificaDesp_02Field;
        
        private string inEspecificaDesp_03Field;
        
        private string inEspecificaDesp_04Field;
        
        private string inEspecificaDesp_05Field;
        
        private string inEspecificaDesp_06Field;
        
        private string inEspecificaDesp_07Field;
        
        private string inEspecificaDesp_08Field;
        
        private string inEspecificaDesp_09Field;
        
        private string inImprimirField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inChave {
            get {
                return this.inChaveField;
            }
            set {
                this.inChaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inImpressora {
            get {
                return this.inImpressoraField;
            }
            set {
                this.inImpressoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inOperador {
            get {
                return this.inOperadorField;
            }
            set {
                this.inOperadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inAplicacao {
            get {
                return this.inAplicacaoField;
            }
            set {
                this.inAplicacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCED {
            get {
                return this.inCEDField;
            }
            set {
                this.inCEDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCFP {
            get {
                return this.inCFPField;
            }
            set {
                this.inCFPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCGC_CPF {
            get {
                return this.inCGC_CPFField;
            }
            set {
                this.inCGC_CPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCodNaturItem {
            get {
                return this.inCodNaturItemField;
            }
            set {
                this.inCodNaturItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inContratoANO {
            get {
                return this.inContratoANOField;
            }
            set {
                this.inContratoANOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inContratoDC {
            get {
                return this.inContratoDCField;
            }
            set {
                this.inContratoDCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inContratoNUM {
            get {
                return this.inContratoNUMField;
            }
            set {
                this.inContratoNUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inContratoORGAO {
            get {
                return this.inContratoORGAOField;
            }
            set {
                this.inContratoORGAOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCredorOrganTipo {
            get {
                return this.inCredorOrganTipoField;
            }
            set {
                this.inCredorOrganTipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inExer {
            get {
                return this.inExerField;
            }
            set {
                this.inExerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inNumNE {
            get {
                return this.inNumNEField;
            }
            set {
                this.inNumNEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inOrgao {
            get {
                return this.inOrgaoField;
            }
            set {
                this.inOrgaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inQuota1 {
            get {
                return this.inQuota1Field;
            }
            set {
                this.inQuota1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inQuota2 {
            get {
                return this.inQuota2Field;
            }
            set {
                this.inQuota2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inQuota3 {
            get {
                return this.inQuota3Field;
            }
            set {
                this.inQuota3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inQuota4 {
            get {
                return this.inQuota4Field;
            }
            set {
                this.inQuota4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inReserva {
            get {
                return this.inReservaField;
            }
            set {
                this.inReservaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inTipoEmpenho {
            get {
                return this.inTipoEmpenhoField;
            }
            set {
                this.inTipoEmpenhoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inTotal {
            get {
                return this.inTotalField;
            }
            set {
                this.inTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inAutFLS {
            get {
                return this.inAutFLSField;
            }
            set {
                this.inAutFLSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCodAssinAutorizacao {
            get {
                return this.inCodAssinAutorizacaoField;
            }
            set {
                this.inCodAssinAutorizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCodAssinExaminado {
            get {
                return this.inCodAssinExaminadoField;
            }
            set {
                this.inCodAssinExaminadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCodAssinRespons {
            get {
                return this.inCodAssinResponsField;
            }
            set {
                this.inCodAssinResponsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCodEspecificaDesp {
            get {
                return this.inCodEspecificaDespField;
            }
            set {
                this.inCodEspecificaDespField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inDestinoRecurso {
            get {
                return this.inDestinoRecursoField;
            }
            set {
                this.inDestinoRecursoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inFonteNE {
            get {
                return this.inFonteNEField;
            }
            set {
                this.inFonteNEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inGrupoAssinAutorizacao {
            get {
                return this.inGrupoAssinAutorizacaoField;
            }
            set {
                this.inGrupoAssinAutorizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inGrupoAssinExaminado {
            get {
                return this.inGrupoAssinExaminadoField;
            }
            set {
                this.inGrupoAssinExaminadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inGrupoAssinRespons {
            get {
                return this.inGrupoAssinResponsField;
            }
            set {
                this.inGrupoAssinResponsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inNumProcesso {
            get {
                return this.inNumProcessoField;
            }
            set {
                this.inNumProcessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inOrgaoAssinAutorizacao {
            get {
                return this.inOrgaoAssinAutorizacaoField;
            }
            set {
                this.inOrgaoAssinAutorizacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inOrgaoAssinExaminado {
            get {
                return this.inOrgaoAssinExaminadoField;
            }
            set {
                this.inOrgaoAssinExaminadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InOrgaoAssinRespons {
            get {
                return this.inOrgaoAssinResponsField;
            }
            set {
                this.inOrgaoAssinResponsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inOrigemRecurso {
            get {
                return this.inOrigemRecursoField;
            }
            set {
                this.inOrigemRecursoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inProcessoNE {
            get {
                return this.inProcessoNEField;
            }
            set {
                this.inProcessoNEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_01 {
            get {
                return this.inEspecificaDesp_01Field;
            }
            set {
                this.inEspecificaDesp_01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_02 {
            get {
                return this.inEspecificaDesp_02Field;
            }
            set {
                this.inEspecificaDesp_02Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_03 {
            get {
                return this.inEspecificaDesp_03Field;
            }
            set {
                this.inEspecificaDesp_03Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_04 {
            get {
                return this.inEspecificaDesp_04Field;
            }
            set {
                this.inEspecificaDesp_04Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_05 {
            get {
                return this.inEspecificaDesp_05Field;
            }
            set {
                this.inEspecificaDesp_05Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_06 {
            get {
                return this.inEspecificaDesp_06Field;
            }
            set {
                this.inEspecificaDesp_06Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_07 {
            get {
                return this.inEspecificaDesp_07Field;
            }
            set {
                this.inEspecificaDesp_07Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_08 {
            get {
                return this.inEspecificaDesp_08Field;
            }
            set {
                this.inEspecificaDesp_08Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inEspecificaDesp_09 {
            get {
                return this.inEspecificaDesp_09Field;
            }
            set {
                this.inEspecificaDesp_09Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inImprimir {
            get {
                return this.inImprimirField;
            }
            set {
                this.inImprimirField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho")]
    public partial class Procedure_ConsultaEmpenhoEstruturaRecordType {
        
        private string outTerminalField;
        
        private string outCEDField;
        
        private string outSucessoField;
        
        private string outCodAplicacaoField;
        
        private string outDispSubEmpenharField;
        
        private string outNrEmpenhoField;
        
        private string outTipoEmpenhoField;
        
        private string outValorAtualField;
        
        private string outValorSubEmpenhadoField;
        
        private string outErroField;
        
        /// <remarks/>
        public string outTerminal {
            get {
                return this.outTerminalField;
            }
            set {
                this.outTerminalField = value;
            }
        }
        
        /// <remarks/>
        public string outCED {
            get {
                return this.outCEDField;
            }
            set {
                this.outCEDField = value;
            }
        }
        
        /// <remarks/>
        public string outSucesso {
            get {
                return this.outSucessoField;
            }
            set {
                this.outSucessoField = value;
            }
        }
        
        /// <remarks/>
        public string outCodAplicacao {
            get {
                return this.outCodAplicacaoField;
            }
            set {
                this.outCodAplicacaoField = value;
            }
        }
        
        /// <remarks/>
        public string outDispSubEmpenhar {
            get {
                return this.outDispSubEmpenharField;
            }
            set {
                this.outDispSubEmpenharField = value;
            }
        }
        
        /// <remarks/>
        public string outNrEmpenho {
            get {
                return this.outNrEmpenhoField;
            }
            set {
                this.outNrEmpenhoField = value;
            }
        }
        
        /// <remarks/>
        public string outTipoEmpenho {
            get {
                return this.outTipoEmpenhoField;
            }
            set {
                this.outTipoEmpenhoField = value;
            }
        }
        
        /// <remarks/>
        public string outValorAtual {
            get {
                return this.outValorAtualField;
            }
            set {
                this.outValorAtualField = value;
            }
        }
        
        /// <remarks/>
        public string outValorSubEmpenhado {
            get {
                return this.outValorSubEmpenhadoField;
            }
            set {
                this.outValorSubEmpenhadoField = value;
            }
        }
        
        /// <remarks/>
        public string outErro {
            get {
                return this.outErroField;
            }
            set {
                this.outErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho")]
    public partial class Procedure_ConsultaEmpenhoEstruturaFiltersType {
        
        private string inChaveField;
        
        private string inImpressoraField;
        
        private string inOperadorField;
        
        private string inAnoField;
        
        private string inCED_1Field;
        
        private string inCED_2Field;
        
        private string inCED_3Field;
        
        private string inCED_4Field;
        
        private string inCED_5Field;
        
        private string inCFP_1Field;
        
        private string inCFP_2Field;
        
        private string inCFP_3Field;
        
        private string inCFP_4Field;
        
        private string inCFP_5Field;
        
        private string inOrgaoField;
        
        private string inOrigemRecursoField;
        
        private string inProcessoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inChave {
            get {
                return this.inChaveField;
            }
            set {
                this.inChaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inImpressora {
            get {
                return this.inImpressoraField;
            }
            set {
                this.inImpressoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inOperador {
            get {
                return this.inOperadorField;
            }
            set {
                this.inOperadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inAno {
            get {
                return this.inAnoField;
            }
            set {
                this.inAnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCED_1 {
            get {
                return this.inCED_1Field;
            }
            set {
                this.inCED_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCED_2 {
            get {
                return this.inCED_2Field;
            }
            set {
                this.inCED_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCED_3 {
            get {
                return this.inCED_3Field;
            }
            set {
                this.inCED_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCED_4 {
            get {
                return this.inCED_4Field;
            }
            set {
                this.inCED_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCED_5 {
            get {
                return this.inCED_5Field;
            }
            set {
                this.inCED_5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCFP_1 {
            get {
                return this.inCFP_1Field;
            }
            set {
                this.inCFP_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCFP_2 {
            get {
                return this.inCFP_2Field;
            }
            set {
                this.inCFP_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCFP_3 {
            get {
                return this.inCFP_3Field;
            }
            set {
                this.inCFP_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCFP_4 {
            get {
                return this.inCFP_4Field;
            }
            set {
                this.inCFP_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inCFP_5 {
            get {
                return this.inCFP_5Field;
            }
            set {
                this.inCFP_5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inOrgao {
            get {
                return this.inOrgaoField;
            }
            set {
                this.inOrgaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inOrigemRecurso {
            get {
                return this.inOrigemRecursoField;
            }
            set {
                this.inOrigemRecursoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inProcesso {
            get {
                return this.inProcessoField;
            }
            set {
                this.inProcessoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho")]
    public partial class Procedure_AnulacaoEmpenhoRecordType {
        
        private string outTerminalField;
        
        private string outCidadeCredorField;
        
        private string outCredor1Field;
        
        private string outCredor2Field;
        
        private string outEnderecoCredorField;
        
        private string outEstadoCredorField;
        
        private string outSaldoAnteriorQ1Field;
        
        private string outSaldoAnteriorQ2Field;
        
        private string outSaldoAnteriorQ3Field;
        
        private string outSaldoAnteriorQ4Field;
        
        private string outSaldoAnteriorTotalField;
        
        private string outSaldoAposAnulQ1Field;
        
        private string outSaldoAposAnulQ2Field;
        
        private string outSaldoAposAnulQ3Field;
        
        private string outSaldoAposAnulQ4Field;
        
        private string outSaldoAposAnulTotalField;
        
        private string outNumAnulacaoEmpField;
        
        private string outSucessoField;
        
        private string outTipoDocField;
        
        private string outErroField;
        
        /// <remarks/>
        public string outTerminal {
            get {
                return this.outTerminalField;
            }
            set {
                this.outTerminalField = value;
            }
        }
        
        /// <remarks/>
        public string outCidadeCredor {
            get {
                return this.outCidadeCredorField;
            }
            set {
                this.outCidadeCredorField = value;
            }
        }
        
        /// <remarks/>
        public string outCredor1 {
            get {
                return this.outCredor1Field;
            }
            set {
                this.outCredor1Field = value;
            }
        }
        
        /// <remarks/>
        public string outCredor2 {
            get {
                return this.outCredor2Field;
            }
            set {
                this.outCredor2Field = value;
            }
        }
        
        /// <remarks/>
        public string outEnderecoCredor {
            get {
                return this.outEnderecoCredorField;
            }
            set {
                this.outEnderecoCredorField = value;
            }
        }
        
        /// <remarks/>
        public string outEstadoCredor {
            get {
                return this.outEstadoCredorField;
            }
            set {
                this.outEstadoCredorField = value;
            }
        }
        
        /// <remarks/>
        public string outSaldoAnteriorQ1 {
            get {
                return this.outSaldoAnteriorQ1Field;
            }
            set {
                this.outSaldoAnteriorQ1Field = value;
            }
        }
        
        /// <remarks/>
        public string outSaldoAnteriorQ2 {
            get {
                return this.outSaldoAnteriorQ2Field;
            }
            set {
                this.outSaldoAnteriorQ2Field = value;
            }
        }
        
        /// <remarks/>
        public string outSaldoAnteriorQ3 {
            get {
                return this.outSaldoAnteriorQ3Field;
            }
            set {
                this.outSaldoAnteriorQ3Field = value;
            }
        }
        
        /// <remarks/>
        public string outSaldoAnteriorQ4 {
            get {
                return this.outSaldoAnteriorQ4Field;
            }
            set {
                this.outSaldoAnteriorQ4Field = value;
            }
        }
        
        /// <remarks/>
        public string outSaldoAnteriorTotal {
            get {
                return this.outSaldoAnteriorTotalField;
            }
            set {
                this.outSaldoAnteriorTotalField = value;
            }
        }
        
        /// <remarks/>
        public string outSaldoAposAnulQ1 {
            get {
                return this.outSaldoAposAnulQ1Field;
            }
            set {
                this.outSaldoAposAnulQ1Field = value;
            }
        }
        
        /// <remarks/>
        public string outSaldoAposAnulQ2 {
            get {
                return this.outSaldoAposAnulQ2Field;
            }
            set {
                this.outSaldoAposAnulQ2Field = value;
            }
        }
        
        /// <remarks/>
        public string outSaldoAposAnulQ3 {
            get {
                return this.outSaldoAposAnulQ3Field;
            }
            set {
                this.outSaldoAposAnulQ3Field = value;
            }
        }
        
        /// <remarks/>
        public string outSaldoAposAnulQ4 {
            get {
                return this.outSaldoAposAnulQ4Field;
            }
            set {
                this.outSaldoAposAnulQ4Field = value;
            }
        }
        
        /// <remarks/>
        public string outSaldoAposAnulTotal {
            get {
                return this.outSaldoAposAnulTotalField;
            }
            set {
                this.outSaldoAposAnulTotalField = value;
            }
        }
        
        /// <remarks/>
        public string outNumAnulacaoEmp {
            get {
                return this.outNumAnulacaoEmpField;
            }
            set {
                this.outNumAnulacaoEmpField = value;
            }
        }
        
        /// <remarks/>
        public string outSucesso {
            get {
                return this.outSucessoField;
            }
            set {
                this.outSucessoField = value;
            }
        }
        
        /// <remarks/>
        public string outTipoDoc {
            get {
                return this.outTipoDocField;
            }
            set {
                this.outTipoDocField = value;
            }
        }
        
        /// <remarks/>
        public string outErro {
            get {
                return this.outErroField;
            }
            set {
                this.outErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho")]
    public partial class EnvironmentVariablesType {
        
        private string domainNameField;
        
        private string serverNameField;
        
        private string sessionIdField;
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServerName {
            get {
                return this.serverNameField;
            }
            set {
                this.serverNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:xmlns:attachmate:vhi-ws:Integracao_DER_SIAFEM_Empenho")]
    public partial class ModelVariablesType {
        
        private string cicsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cics {
            get {
                return this.cicsField;
            }
            set {
                this.cicsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Procedure_AnulacaoEmpenhoCompletedEventHandler(object sender, Procedure_AnulacaoEmpenhoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Procedure_AnulacaoEmpenhoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Procedure_AnulacaoEmpenhoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Procedure_AnulacaoEmpenhoRecordType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Procedure_AnulacaoEmpenhoRecordType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Procedure_ConsultaEmpenhoEstruturaCompletedEventHandler(object sender, Procedure_ConsultaEmpenhoEstruturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Procedure_ConsultaEmpenhoEstruturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Procedure_ConsultaEmpenhoEstruturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Procedure_ConsultaEmpenhoEstruturaRecordType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Procedure_ConsultaEmpenhoEstruturaRecordType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Procedure_InclusaoEmpenhoCompletedEventHandler(object sender, Procedure_InclusaoEmpenhoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Procedure_InclusaoEmpenhoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Procedure_InclusaoEmpenhoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Procedure_InclusaoEmpenhoRecordType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Procedure_InclusaoEmpenhoRecordType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Procedure_ReforcoEmpenhoCompletedEventHandler(object sender, Procedure_ReforcoEmpenhoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Procedure_ReforcoEmpenhoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Procedure_ReforcoEmpenhoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Procedure_ReforcoEmpenhoRecordType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Procedure_ReforcoEmpenhoRecordType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void wsResourceCreateCompletedEventHandler(object sender, wsResourceCreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsResourceCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsResourceCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void wsResourceDestroyCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591