//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Sids.Prodesp.Infrastructure.siafemProd {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RecebeMSGSoap", Namespace="https://www.bec.sp.gov.br/SIAFISICO/RecebeMSG/")]
    public partial class RecebeMSG : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MensagemOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RecebeMSG() {
            this.Url = global::Sids.Prodesp.Infrastructure.Properties.Settings.Default.Sids_Prodesp_Infrastructure_siafemProd_RecebeMSG;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MensagemCompletedEventHandler MensagemCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.bec.sp.gov.br/SIAFISICO/RecebeMSG/Mensagem", RequestNamespace="https://www.bec.sp.gov.br/SIAFISICO/RecebeMSG/", ResponseNamespace="https://www.bec.sp.gov.br/SIAFISICO/RecebeMSG/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Mensagem(string Usuario, string Senha, string AnoBase, string UnidadeGestora, string DocumentoXML) {
            object[] results = this.Invoke("Mensagem", new object[] {
                        Usuario,
                        Senha,
                        AnoBase,
                        UnidadeGestora,
                        DocumentoXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MensagemAsync(string Usuario, string Senha, string AnoBase, string UnidadeGestora, string DocumentoXML) {
            this.MensagemAsync(Usuario, Senha, AnoBase, UnidadeGestora, DocumentoXML, null);
        }
        
        /// <remarks/>
        public void MensagemAsync(string Usuario, string Senha, string AnoBase, string UnidadeGestora, string DocumentoXML, object userState) {
            if ((this.MensagemOperationCompleted == null)) {
                this.MensagemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMensagemOperationCompleted);
            }
            this.InvokeAsync("Mensagem", new object[] {
                        Usuario,
                        Senha,
                        AnoBase,
                        UnidadeGestora,
                        DocumentoXML}, this.MensagemOperationCompleted, userState);
        }
        
        private void OnMensagemOperationCompleted(object arg) {
            if ((this.MensagemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MensagemCompleted(this, new MensagemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void MensagemCompletedEventHandler(object sender, MensagemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MensagemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MensagemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591