namespace Sids.Prodesp.Model.Enum
{
    public enum EnumURL
    {
        ListarPerfil,
        CadastrarPerfil,
        ListarFuncionalidade,
        CadastrarFuncionalidade,
        ListarLog,
        ListarUsuario,
        CadastrarUsuario,
        AlterarSenha,
        ListarFonte,
        CadastrarFonte,
        ListarPrograma,
        CadastrarPrograma,
        ListarEstrutura,
        CadastrarEstrutura,
        ListarReserva,
        CadastrarReserva,
        ListarReservaReforco,
        CadastrarReservaReforco,
        ListarReservaCancelamento,
        CadastrarReservaCancelamento,
        ListarEmpenho,
        CadastrarEmpenho,
        ListarEmpenhoReforco,
        CadastrarEmpenhoReforco,
        ListarEmpenhoCancelamento,
        CadastrarEmpenhoCancelamento,
        ListarSubempenho,
        ListarSubempenhoCancelamento,
        ListarRapInscricao,
        ListarRapRequisicao,
        ListarRapAnulacao
    }
}
