-- ===================================================================  
-- Author:		Carlos Henrique Magalhães
-- Create date: 31/03/2017
-- Description: Procedure para consultar uma requisição de rap
-- =================================================================== 
CREATE procedure [dbo].[PR_RAP_REQUISICAO_SELECIONAR]
	@id_rap_requisicao int
as  
begin  
  
 SET NOCOUNT ON;  
  
	SELECT TOP 1
			[id_rap_requisicao]
      ,[tb_estrutura_id_estrutura]
      ,[tb_natureza_tipo_id_natureza_tipo]
      ,[tb_servico_tipo_id_servico_tipo]
      ,[tb_regional_id_regional]
      ,[nr_prodesp]
      ,[nr_siafem_siafisico]
      ,[nr_prodesp_original]
      ,[nr_empenho_siafem_siafisico]
      ,[nr_subempenho]
      ,[nr_cnpj_cpf_credor]
      ,[cd_gestao_credor]
      ,[nr_despesa_processo]
      ,[nr_recibo]
      ,[nr_contrato]
      ,[cd_unidade_gestora]
      ,[cd_aplicacao_obra]
      ,[cd_unidade_gestora_obra]
      ,[cd_gestao]
      ,[cd_gestao_fornecedora]
      ,[vl_valor]
      ,[vl_realizado]
      ,[vl_caucao_caucionado]
      ,[cd_nota_fiscal_prodesp]
      ,[cd_tarefa]
	  ,[tarefa]
      ,[nr_classificacao]
      ,[nr_ano_medicao]
      ,[nr_mes_medicao]
      ,[ds_prazo_pagamento]
      ,[dt_realizado]
      ,[ds_despesa_referencia]
      ,[ds_nl_retencao_inss]
      ,[ds_lista]
      ,[ds_despesa_autorizado_supra_folha]
      ,[ds_observacao_1]
      ,[ds_observacao_2]
      ,[ds_observacao_3]
      ,[nr_medicao]
      ,[cd_despesa]
      ,[cd_despesa_especificacao_despesa]
      ,[ds_despesa_especificacao_1]
      ,[ds_despesa_especificacao_2]
      ,[ds_despesa_especificacao_3]
      ,[ds_despesa_especificacao_4]
      ,[ds_despesa_especificacao_5]
      ,[ds_despesa_especificacao_6]
      ,[ds_despesa_especificacao_7]
      ,[ds_despesa_especificacao_8]
      ,[cd_assinatura_autorizado]
      ,[cd_assinatura_autorizado_grupo]
      ,[cd_assinatura_autorizado_orgao]
      ,[ds_assinatura_autorizado_cargo]
      ,[nm_assinatura_autorizado]
      ,[cd_assinatura_examinado]
      ,[cd_assinatura_examinado_grupo]
      ,[cd_assinatura_examinado_orgao]
      ,[ds_assinatura_examinado_cargo]
      ,[nm_assinatura_examinado]
      ,[cd_assinatura_responsavel]
      ,[cd_assinatura_responsavel_grupo]
      ,[cd_assinatura_responsavel_orgao]
      ,[ds_assinatura_responsavel_cargo]
      ,[nm_assinatura_responsavel]
      ,[nm_caucao_autorizado_por]
      ,[nm_dados_caucao]
      ,[cd_transmissao_status_prodesp]
      ,[fl_transmissao_transmitido_prodesp]
      ,[fl_sistema_prodesp]
      ,[dt_transmissao_transmitido_prodesp]
      ,[ds_transmissao_mensagem_prodesp]
      ,[cd_transmissao_status_siafem_siafisico]
      ,[fl_transmissao_transmitido_siafem_siafisico]
      ,[fl_sistema_siafem_siafisico]
      ,[dt_transmissao_transmitido_siafem_siafisico]
      ,[dt_cadastro]
      ,[dt_emissao]
      ,[ds_transmissao_mensagem_siafem_siafisico]
      ,[fl_documento_completo]
      ,[fl_documento_status]
      ,[fl_sistema_siafisico]
      ,[cd_transmissao_status_siafisico]
      ,[fl_transmissao_transmitido_siafisico]
      ,[cd_cenario_prodesp]
      ,[tb_programa_id_programa]
      ,[nr_caucao_guia]
      ,[nm_caucao_quota_geral_autorizado_por]
      ,[cd_credor_organizacao]
      ,[nr_cnpj_cpf_fornecedor]
	  ,[dt_vencimento]
	  ,[fl_referencia_digitada]
	  ,[nr_empenho]
		
	FROM pagamento.tb_rap_requisicao (nolock)
	where
		( id_rap_requisicao = @id_rap_requisicao )
   
end;