-- ===================================================================  
-- Author:		Rodrigo Cesar de Freitas
-- Create date: 09/02/2017
-- Description: Procedure para consultar subempenhos
-- =================================================================== 
CREATE procedure [dbo].[PR_SUBEMPENHO_SELECIONAR]
	@id_subempenho int
as  
begin  
  
 SET NOCOUNT ON;  
  
	SELECT TOP 1
		[id_subempenho]
      ,[dt_cadastro]
      ,[fl_sistema_prodesp]
      ,[fl_sistema_siafem_siafisico]
      ,[fl_sistema_siafisico]
      ,[nr_prodesp]
      ,[nr_siafem_siafisico]
      ,[nr_contrato]
      ,[tb_cenario_id_cenario]
      ,[nr_empenho_prodesp]
      ,[cd_tarefa]
      ,[cd_despesa]
      ,[vl_realizado]
      ,[nr_recibo]
      ,[ds_prazo_pagamento]
      ,[dt_realizado]
	  ,[dt_vencimento]
      ,[cd_cenario_prodesp]
      ,[nr_ct]
      ,[nr_empenho_siafem_siafisico]
      ,[cd_unidade_gestora]
      ,[cd_gestao]
      ,[cd_nota_fiscal_prodesp]
      ,[nr_medicao]
      ,[tb_natureza_tipo_id_natureza_tipo]
      ,[vl_valor]
      ,[cd_evento]
      ,[dt_emissao]
      ,[tb_evento_tipo_id_evento_tipo]
      ,[nr_cnpj_cpf_credor]
      ,[cd_gestao_credor]
      ,[nr_ano_medicao]
      ,[nr_mes_medicao]
      ,[nr_percentual]
      ,[tb_regional_id_regional]
      ,[tb_programa_id_programa]
      ,[tb_estrutura_id_estrutura]
      ,[tb_fonte_id_fonte]
      ,[cd_aplicacao_obra]
      ,[tb_obra_tipo_id_obra_tipo]
	  ,[cd_obra_tipo]
	  ,[nr_obra]
      ,[cd_unidade_gestora_obra]
      ,[cd_credor_organizacao]
      ,[nr_cnpj_cpf_fornecedor]
      ,[ds_observacao_1]
      ,[ds_observacao_2]
      ,[ds_observacao_3]
      ,[nr_despesa_processo]
      ,[ds_nl_retencao_inss]
      ,[ds_lista]
      ,[ds_despesa_referencia]
      ,[ds_despesa_autorizado_supra_folha]
      ,[cd_despesa_especificacao_despesa]
      ,[ds_despesa_especificacao_1]
      ,[ds_despesa_especificacao_2]
      ,[ds_despesa_especificacao_3]
      ,[ds_despesa_especificacao_4]
      ,[ds_despesa_especificacao_5]
      ,[ds_despesa_especificacao_6]
      ,[ds_despesa_especificacao_7]
      ,[ds_despesa_especificacao_8]
      ,[ds_despesa_especificacao_9]
      ,[cd_assinatura_autorizado]
      ,[cd_assinatura_autorizado_grupo]
      ,[cd_assinatura_autorizado_orgao]
      ,[ds_assinatura_autorizado_cargo]
      ,[nm_assinatura_autorizado]
      ,[cd_assinatura_examinado]
      ,[cd_assinatura_examinado_grupo]
      ,[cd_assinatura_examinado_orgao]
      ,[ds_assinatura_examinado_cargo]
      ,[nm_assinatura_examinado]
      ,[cd_assinatura_responsavel]
      ,[cd_assinatura_responsavel_grupo]
      ,[cd_assinatura_responsavel_orgao]
      ,[ds_assinatura_responsavel_cargo]
      ,[nm_assinatura_responsavel]
      ,[nr_caucao_guia]
      ,[nm_caucao_quota_geral_autorizado_por]
      ,[vl_caucao_caucionado]
      ,[cd_transmissao_status_prodesp]
      ,[fl_transmissao_transmitido_prodesp]
      ,[dt_transmissao_transmitido_prodesp]
      ,[ds_transmissao_mensagem_prodesp]
      ,[cd_transmissao_status_siafem_siafisico]
      ,[fl_transmissao_transmitido_siafem_siafisico]
      ,[dt_transmissao_transmitido_siafem_siafisico]
      ,[ds_transmissao_mensagem_siafem_siafisico]
      ,[fl_documento_completo]
      ,[fl_documento_status]
      ,[cd_transmissao_status_siafisico]
      ,[fl_transmissao_transmitido_siafisico]
	  ,[nm_credor]
	  ,[fl_referencia_digitada]
	FROM pagamento.tb_subempenho (nolock)
	where
		( id_subempenho = @id_subempenho )
   
end;