//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sids.Prodesp.Infrastructure.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200164")]
        public string UnidadeGestora {
            get {
                return ((string)(this["UnidadeGestora"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://siafemhom.intra.fazenda.sp.gov.br/siafisico/RecebeMSG.asmx")]
        public string siafem {
            get {
                return ((string)(this["siafem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://siafemhom.intra.fazenda.sp.gov.br/siafisico/RecebeMSG.asmx")]
        public string Sids_Prodesp_Infrastructure_Siafem_RecebeMSG {
            get {
                return ((string)(this["Sids_Prodesp_Infrastructure_Siafem_RecebeMSG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.200.142.198:9680/vhi-xe/session/Pool_IntegracaoReserva")]
        public string Sids_Prodesp_Prodesp_Reserva_Desevolvomento {
            get {
                return ((string)(this["Sids_Prodesp_Prodesp_Reserva_Desevolvomento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www6.fazenda.sp.gov.br/siafisico/RecebeMSG.asmx")]
        public string Sids_Prodesp_Infrastructure_siafemProd_RecebeMSG {
            get {
                return ((string)(this["Sids_Prodesp_Infrastructure_siafemProd_RecebeMSG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.200.77.62:9680/vhi-xe/session/Pool_IntegracaoReserva")]
        public string Sids_Prodesp_Prodesp_Reserva_Homologacao {
            get {
                return ((string)(this["Sids_Prodesp_Prodesp_Reserva_Homologacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.200.77.62:9680/vhi-xe/session/Pool_IntegracaoReserva")]
        public string Sids_Prodesp_Prodesp_Reserva_Producao {
            get {
                return ((string)(this["Sids_Prodesp_Prodesp_Reserva_Producao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.200.142.198:9680/vhi-xe/session/Pool_IntegracaoEmpenho")]
        public string Sids_Prodesp_Prodesp_Empenho_Desevolvomento {
            get {
                return ((string)(this["Sids_Prodesp_Prodesp_Empenho_Desevolvomento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.200.77.62:9680/vhi-xe/session/Pool_IntegracaoEmpenho")]
        public string Sids_Prodesp_Prodesp_Empenho_Homologacao {
            get {
                return ((string)(this["Sids_Prodesp_Prodesp_Empenho_Homologacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.200.77.62:9680/vhi-xe/session/Pool_IntegracaoEmpenho")]
        public string Sids_Prodesp_Prodesp_Empenho_Producao {
            get {
                return ((string)(this["Sids_Prodesp_Prodesp_Empenho_Producao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.200.142.198:9680/vhi-xe/session/Pool_IntegracaoLiqDespesas")]
        public string Sids_Prodesp_Infrastructure_ProdespLiquidacaoDespesa_Integracao_DER_SIAFEM_LiqDespesasService {
            get {
                return ((string)(this["Sids_Prodesp_Infrastructure_ProdespLiquidacaoDespesa_Integracao_DER_SIAFEM_LiqDes" +
                    "pesasService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.72.1.40:9680/vhi-xe/session/Pool_IntegracaoPagtoContaUnica")]
        public string Sids_Prodesp_Infrastructure_ProdespPagtoContaUnica_Integracao_DER_SIAFEM_PagtoContaUnicaService {
            get {
                return ((string)(this["Sids_Prodesp_Infrastructure_ProdespPagtoContaUnica_Integracao_DER_SIAFEM_PagtoCon" +
                    "taUnicaService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.200.142.198:9680/vhi-xe/session/Pool_IntegracaoPagtoContaDER")]
        public string Sids_Prodesp_Infrastructure_ProdespPagamentoContaDer_Integracao_DER_SIAFEM_PagtoContaDERService {
            get {
                return ((string)(this["Sids_Prodesp_Infrastructure_ProdespPagamentoContaDer_Integracao_DER_SIAFEM_PagtoC" +
                    "ontaDERService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.200.142.198:9680/vhi-xe/session/Pool_IntegracaoMovOrcamentaria")]
        public string Sids_Prodesp_Infrastructure_ProdespMovimentacao_Integracao_DER_SIAFEM_MovOrcamentariaService {
            get {
                return ((string)(this["Sids_Prodesp_Infrastructure_ProdespMovimentacao_Integracao_DER_SIAFEM_MovOrcament" +
                    "ariaService"]));
            }
        }
    }
}
