CREATE TABLE [contaunica].[tb_arquivo_remessa] (
    [id_arquivo_remessa]         INT           IDENTITY (1, 1) NOT NULL,
    [tb_arquivo_id_arquivo]      INT           NULL,
    [nr_geracao_arquivo]         INT           NULL,
    [dt_preparacao_pagamento]    DATETIME      NULL,
    [dt_pagamento]               DATETIME      NULL,
    [cd_assinatura]              VARCHAR (5)   NULL,
    [cd_grupo_assinatura]        VARCHAR (1)   NULL,
    [cd_orgao_assinatura]        VARCHAR (2)   NULL,
    [nm_assinatura]              VARCHAR (55)  NULL,
    [ds_cargo]                   VARCHAR (55)  NULL,
    [cd_contra_assinatura]       VARCHAR (5)   NULL,
    [cd_grupo_contra_assinatura] VARCHAR (1)   NULL,
    [cd_orgao_contra_assinatura] VARCHAR (2)   NULL,
    [nm_contra_assinatura]       VARCHAR (55)  NULL,
    [ds_cargo_contra_assinatura] VARCHAR (55)  NULL,
    [cd_conta]                   INT           NULL,
    [ds_banco]                   VARCHAR (50)  NULL,
    [ds_agencia]                 VARCHAR (50)  NULL,
    [ds_conta]                   VARCHAR (50)  NULL,
    [qt_ordem_pagamento_arquivo] INT           NULL,
    [qt_deposito_arquivo]        INT           NULL,
    [vr_total_pago]              INT           NULL,
    [qt_doc_ted_arquivo]         INT           NULL,
    [dt_cadastro]                DATETIME      NULL,
    [fg_trasmitido_prodesp]      CHAR (1)      NULL,
    [dt_trasmitido_prodesp]      DATETIME      NULL,
    [fg_arquivo_cancelado]       BIT           NULL,
    [id_regional]                SMALLINT      NULL,
    [bl_cadastro_completo]       BIT           NULL,
    [ds_msg_retorno]             VARCHAR (256) NULL,
    [bl_transmitir_prodesp]      BIT           NULL,
    [bl_transmitido_prodesp]     BIT           NULL,
    CONSTRAINT [PK_tb_arquivo_remessa] PRIMARY KEY CLUSTERED ([id_arquivo_remessa] ASC),
    CONSTRAINT [FK_tb_arquivo_remessa_tb_regional] FOREIGN KEY ([id_regional]) REFERENCES [seguranca].[tb_regional] ([id_regional])
);



